version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-api-img:1.0.0
    container_name: node-express-api
    ports:
      - '3000:3000'
    volumes:
      - .:/app
